"""Update rebooks table

Revision ID: 14dc6a80ad8a
Revises: 1885bd609977
Create Date: 2025-01-28 05:04:51.121043

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14dc6a80ad8a"
down_revision: Union[str, None] = "1885bd609977"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
