"""Update all tables

Revision ID: 9bcf82d83ee2
Revises: 14dc6a80ad8a
Create Date: 2025-02-01 03:02:27.855235

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9bcf82d83ee2"
down_revision: Union[str, None] = "14dc6a80ad8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "authors", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "authors", type_="unique")
    # ### end Alembic commands ###
